language: objective-c
osx_image: xcode8.2
sudo: false

before_install:
	- gem install fastlane

before_script:
	- fastlane snapshot reset_simulators --force

script:
	- xcodebuild clean build test -project ManualJayout.xcodeproj -scheme ManualJayout -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2"
